# Copyright 2022 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.secrets }}
{{- range $secret := .Values.secrets }}
apiVersion: v1
data:
  {{- range $keyValue := $secret.keyValues }}
  {{ $keyValue.key }}: {{ $keyValue.value }}
  {{- end }}
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
type: {{ $secret.type }}
{{- end }}
{{- end }}
