replicaCount: 3

image:
  repository: 150476025846.dkr.ecr.eu-west-2.amazonaws.com/aide/front-end
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
 - name: regcred

enviromentVariables:
  KEYCLOAK_URL: https://dev-aide.answerdigital.io:8443/auth
  FRONTEND_API_HOST: http://dev-aide.answerdigital.io:5000
  ORTHANC_API_URL: https://dev-aide.answerdigital.io:8045
  VUE_APP_AUTH_ENABLED: true

ingress:
  host: sit-aide.answerdigital.io
  tlsSecretName: certificatesecret

service:
  type: ClusterIP
  port: 80

volumes:
  - name: aide-storage
    claimName: aide-frontend-pvc

volumeMounts:
  - name: aide-storage
    mountPath: /aide/data

storage:
  globalStorageClassName: global-sc
  globalDataDirectory: /efs_data/aide/
  storageClassName: aide-sc
  storageClaimName: aide-frontend-pvc
  dataDirectory: /efs_data/aide/data/
  dataVolumeLabel: aide-frontend
  dataStorageCapacityRequest: 10Gi
