replicaCount: 3

image:
  repository: 150476025846.dkr.ecr.eu-west-2.amazonaws.com/aide/front-end
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets:
 - name: regcred

enviromentVariables:
  KEYCLOAK_URL: https://dev-aide.answerdigital.io:8443/auth
  VUE_APP_AUTH_ENABLED: true
  FRONTEND_API_HOST: https://sit-aide.answerdigital.io/api/
      
ingress:
  host: sit-aide.answerdigital.io
  tlsSecretName: certificatesecret

service:
  type: ClusterIP
  port: 80  
 