name: License Finder

on:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' 
        bundler-cache: true 
    - name: Install License Finder tool with Ruby
      run: gem install license_finder
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - name: Perform License Scanning
      id: license_scanning
      run: license_finder
    - name: Check this step to see how to resolve failure with license scanning
      if: ${{ failure() && steps.license_scanning.conclusion == 'failure' }}
      run: echo "You have added a new package that needs to be manually checked to ensure it fits our license allowances. Please read the 'License Scanning' section of the 'CONTRIBUTING.MD' file to see what the next steps are."