name: 'pull-requests'

# Controls when the workflow will run
on:
  pull_request:

jobs:
  Test-UI-Headless:
    runs-on: ubuntu-latest

    container:
      image: cypress/included:10.7.0
      options: --user 1001
      env:
        VUE_APP_AUTH_ENABLED: false
        CYPRESS_CACHE_FOLDER: '${GITHUB_WORKSPACE}/.cypress-cache'

    steps:
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-

      - uses: actions/checkout@v3
      - run: npm ci --cache .npm --prefer-offline
      - run: npm run tests:ui_ci
      - run: cp -r ${GITHUB_WORKSPACE}/.cypress-cache/screenshots ci_artifacts/
        continue-on-error: true

      - name: Archive CI artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-ui-headless-$GITHUB_RUN_ID
          path: ci_artifacts/
