name: 'Test'

on:
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run serve:cypress
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 240
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots