docker-build:
  stage: build-image
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export DOCKER_IMAGE_TAG="registry.gitlab.com/answerdigital/londonai/aide/aide-frontend:$CI_PIPELINE_IID"
    - export DOCKER_LATEST_TAG="registry.gitlab.com/answerdigital/londonai/aide/micro-services/aide-frontend:latest"
    - echo "Building docker image for version $DOCKER_IMAGE_TAG"
    - docker build --pull -t "$DOCKER_IMAGE_TAG" .
    - echo "Pushing docker image"
    - docker push "$DOCKER_IMAGE_TAG"
    - docker tag "$DOCKER_IMAGE_TAG" "$DOCKER_LATEST_TAG"
    - docker push "$DOCKER_LATEST_TAG"
  only:
    - main
    - /^release-.*$/

docker-build-branch:
  stage: build-image
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - export DOCKER_IMAGE_TAG="registry.gitlab.com/answerdigital/londonai/aide/aide-frontend:$CI_COMMIT_BRANCH"
    - echo "Building docker image for version $DOCKER_IMAGE_TAG"
    - docker build --pull -t "$DOCKER_IMAGE_TAG" .
    - echo "Pushing docker image"
    - docker push "$DOCKER_IMAGE_TAG"
  when:
    - manual

