include:
  - /.gitlab/templates/.cr.yml

stages:
  - lint
  - sast
  - check-build-integrity
  - test-ui-integration
  - contracts
  - build-image
  - deploy

variables:
  TEMP_DIR: "temp-$CI_PROJECT_NAME-job_id-$CI_JOB_ID-job_time_utc-$CI_JOB_STARTED_AT"

deploy dev:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - apt update
    - apt -y install openssh-server
    - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_KEY
    - cat $ANSIBLE_DEPLOY_EXTRA_VARS > ansible-deploy-extra-vars.yml
    - aws configure set region eu-west-2
    - mkdir -p ~/.ssh
    - aws secretsmanager get-secret-value --secret-id $DEV_ANSIBLE_CONTROL_KEY --query SecretString --output text > ~/.ssh/$DEV_ANSIBLE_CONTROL_KEY
    - chmod 400 ~/.ssh/$DEV_ANSIBLE_CONTROL_KEY
    - echo -e "\nIdentityFile ~/.ssh/$DEV_ANSIBLE_CONTROL_KEY" >> ~/.ssh/config
    - ssh-keyscan -H $DEV_ANSIBLE_CONTROL_IP >> ~/.ssh/known_hosts
    - ssh ubuntu@$DEV_ANSIBLE_CONTROL_IP "mkdir $TEMP_DIR"
    - scp ansible-deploy-extra-vars.yml ubuntu@$DEV_ANSIBLE_CONTROL_IP:$TEMP_DIR
    - ssh ubuntu@$DEV_ANSIBLE_CONTROL_IP "
      cd $TEMP_DIR;
      sudo aws s3 cp s3://ansible-tools-$DEV_ANSIBLE_TOOLS_BUCKET/ansible-schedule-ubuntu.sh /home/ubuntu/$TEMP_DIR;
      sudo apt -y install dos2unix;
      sudo dos2unix /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo chmod +x /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh -a create -e dev -p aws-deploy-service.yml -v @/home/ubuntu/$TEMP_DIR/ansible-deploy-extra-vars.yml"
  after_script:
    - ssh ubuntu@$DEV_ANSIBLE_CONTROL_IP "sudo rm -r /home/ubuntu/$TEMP_DIR"
  only:
    - develop

deploy branch:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - apt update
    - apt -y install openssh-server
    - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_KEY
    - cat $ANSIBLE_DEPLOY_EXTRA_VARS > ansible-deploy-extra-vars.yml
    - aws configure set region eu-west-2
    - mkdir -p ~/.ssh
    - aws secretsmanager get-secret-value --secret-id $DEV_ANSIBLE_CONTROL_KEY --query SecretString --output text > ~/.ssh/$DEV_ANSIBLE_CONTROL_KEY
    - chmod 400 ~/.ssh/$DEV_ANSIBLE_CONTROL_KEY
    - echo -e "\nIdentityFile ~/.ssh/$DEV_ANSIBLE_CONTROL_KEY" >> ~/.ssh/config
    - ssh-keyscan -H $DEV_ANSIBLE_CONTROL_IP >> ~/.ssh/known_hosts
    - ssh ubuntu@$DEV_ANSIBLE_CONTROL_IP "mkdir $TEMP_DIR"
    - scp ansible-deploy-extra-vars.yml ubuntu@$DEV_ANSIBLE_CONTROL_IP:$TEMP_DIR
    - ssh ubuntu@$DEV_ANSIBLE_CONTROL_IP "
      cd $TEMP_DIR;
      sudo aws s3 cp s3://ansible-tools-$DEV_ANSIBLE_TOOLS_BUCKET/ansible-schedule-ubuntu.sh /home/ubuntu/$TEMP_DIR;
      sudo apt -y install dos2unix;
      sudo dos2unix /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo chmod +x /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh -a create -e dev -p aws-deploy-service.yml -v @/home/ubuntu/$TEMP_DIR/ansible-deploy-extra-vars.yml"
  after_script:
    - ssh ubuntu@$DEV_ANSIBLE_CONTROL_IP "sudo rm -r /home/ubuntu/$TEMP_DIR"
  when:
    - manual

deploy sit:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - echo $SIT_ANSIBLE_CONTROL_KEY
    - echo $SIT_ANSIBLE_CONTROL_IP
    - apt update
    - apt -y install openssh-server
    - export AWS_ACCESS_KEY_ID=$SIT_AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$SIT_AWS_SECRET_KEY
    - cat $ANSIBLE_DEPLOY_EXTRA_VARS > ansible-deploy-extra-vars.yml
    - aws configure set region eu-west-2
    - mkdir -p ~/.ssh
    - aws secretsmanager get-secret-value --secret-id $SIT_ANSIBLE_CONTROL_KEY --query SecretString --output text > ~/.ssh/$SIT_ANSIBLE_CONTROL_KEY
    - chmod 400 ~/.ssh/$SIT_ANSIBLE_CONTROL_KEY
    - echo -e "\nIdentityFile ~/.ssh/$SIT_ANSIBLE_CONTROL_KEY" >> ~/.ssh/config
    - ssh-keyscan -H $SIT_ANSIBLE_CONTROL_IP >> ~/.ssh/known_hosts
    - ssh ubuntu@$SIT_ANSIBLE_CONTROL_IP "mkdir $TEMP_DIR"
    - scp ansible-deploy-extra-vars.yml ubuntu@$SIT_ANSIBLE_CONTROL_IP:$TEMP_DIR
    - ssh ubuntu@$SIT_ANSIBLE_CONTROL_IP "
      cd $TEMP_DIR;
      sudo aws s3 cp s3://ansible-tools-$SIT_ANSIBLE_TOOLS_BUCKET/ansible-schedule-ubuntu.sh /home/ubuntu/$TEMP_DIR;
      sudo apt -y install dos2unix;
      sudo dos2unix /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo chmod +x /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh -a create -e sit -p aws-deploy-service.yml -v @/home/ubuntu/$TEMP_DIR/ansible-deploy-extra-vars.yml"
  after_script:
    - ssh ubuntu@$SIT_ANSIBLE_CONTROL_IP "sudo rm -r /home/ubuntu/$TEMP_DIR"
  only:
    - main
    - /^release-.*$/

deploy uat:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - echo $UAT_ANSIBLE_CONTROL_KEY
    - echo $UAT_ANSIBLE_CONTROL_IP
    - apt update
    - apt -y install openssh-server
    - export AWS_ACCESS_KEY_ID=$UAT_AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$UAT_AWS_SECRET_KEY
    - cat $ANSIBLE_DEPLOY_EXTRA_VARS > ansible-deploy-extra-vars.yml
    - aws configure set region eu-west-2
    - mkdir -p ~/.ssh
    - aws secretsmanager get-secret-value --secret-id $UAT_ANSIBLE_CONTROL_KEY --query SecretString --output text > ~/.ssh/$UAT_ANSIBLE_CONTROL_KEY
    - chmod 400 ~/.ssh/$UAT_ANSIBLE_CONTROL_KEY
    - echo -e "\nIdentityFile ~/.ssh/$UAT_ANSIBLE_CONTROL_KEY" >> ~/.ssh/config
    - ssh-keyscan -H $UAT_ANSIBLE_CONTROL_IP >> ~/.ssh/known_hosts
    - ssh ubuntu@$UAT_ANSIBLE_CONTROL_KEY "mkdir $TEMP_DIR"
    - scp ansible-deploy-extra-vars.yml ubuntu@$UAT_ANSIBLE_CONTROL_KEY:$TEMP_DIR
    - ssh ubuntu@$UAT_ANSIBLE_CONTROL_KEY "
      cd $TEMP_DIR;
      sudo aws s3 cp s3://ansible-tools-$UAT_ANSIBLE_CONTROL_KEY/ansible-schedule-ubuntu.sh /home/ubuntu/$TEMP_DIR;
      sudo apt -y install dos2unix;
      sudo dos2unix /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo chmod +x /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh;
      sudo /home/ubuntu/$TEMP_DIR/ansible-schedule-ubuntu.sh -a create -e uat -p aws-deploy-service.yml -v @/home/ubuntu/$TEMP_DIR/ansible-deploy-extra-vars.yml"
  after_script:
    - ssh ubuntu@$UAT_ANSIBLE_CONTROL_KEY "sudo rm -r /home/ubuntu/$TEMP_DIR"
  rules:
      - if: '$CI_PIPELINE_SOURCE == "web" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /^release-.*$/)'
        when: always
